# -*- coding: utf-8 -*-
"""App_Garmin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NU7lyq1sQAme8_7wKWdlSZNqvpixGcEQ
"""

import streamlit as st
import pandas as pd
import numpy as np
import datetime
import sqlite3
import os
import io
import csv
import re
import base64

# --- CONFIGURATION ---
DB_PATH = "evolution_data.db" # Modifié temporairement pour le Cloud en attendant demain
LOGO_PATH = "https://raw.githubusercontent.com/adnielmehdiahcene/TrainSmart-DZ/main/Gemini_Generated_Image_.png"

# --- STYLE CSS INTEGRAL ---
st.markdown("""
<style>
    .kpi-container {
        display: flex; flex-direction: column; align-items: center; justify-content: center;
        padding: 15px; background-color: rgba(255, 255, 255, 0.05); border-radius: 10px;
        min-height: 120px;
    }
    .status-row { display: flex; align-items: center; gap: 10px; margin-top: 5px; }
    .status-circle { text-shadow: 0px 0px 8px rgba(0,0,0,0.6); font-size: 1.3em; }
    .trend-arrow { color: #94a3b8; font-size: 1em; font-weight: bold; }
    .sidebar-logo { display: block; margin: 0 auto 20px auto; width: 120px; border-radius: 20px; border: 2px solid #1E3A8A; }
    [data-testid="stMetricValue"] { font-size: 1.8rem !important; font-weight: bold !important; }
</style>
""", unsafe_allow_html=True)

# --- FONCTIONS SYSTÈME VITALES ---
def init_db():
    conn = sqlite3.connect(DB_PATH)
    conn.execute('CREATE TABLE IF NOT EXISTS evolution (date TEXT, nom TEXT, phase TEXT, rei REAL, drift REAL, score REAL)')
    conn.commit()
    conn.close()

def get_base64_of_bin_file(bin_file):
    with open(bin_file, 'rb') as f:
        return base64.b64encode(f.read()).decode()

def smart_parse_time(val):
    try:
        p = str(val).split(':')
        if len(p) == 2: return int(p[0])*60 + float(p[1])
        if len(p) == 3: return int(p[0])*3600 + int(p[1])*60 + float(p[2])
        return float(val)
    except: return 0.0

# --- DICTIONNAIRE SCIENTIFIQUE INTERNATIONAL (8 KPIs) ---
NORMS = {
    "REI": {"blue": 1.05, "green": 1.20, "label": "Efficience Énergétique", "unit": "W/kg/(m/s)", "ref": "Daniels (1985)", "def": "Indice d'économie de course. Mesure la quantité de puissance déployée pour maintenir une vitesse donnée par kilogramme."},
    "Pa:Hr": {"blue": 5.0, "green": 10.0, "label": "Dérive Cardiaque (Drift)", "unit": "%", "ref": "Joe Friel", "def": "Découplage entre la charge externe (Watts) et interne (FC). Reflète la fatigue ou la dérive thermique."},
    "W/KG": {"blue": 4.5, "green": 3.5, "label": "Power/Weight", "unit": "W/kg", "ref": "Coggan", "def": "Puissance brute normalisée par le poids de l'athlète. Indicateur clé du potentiel de relance et de grimpe."},
    "VR": {"blue": 7.0, "green": 9.5, "label": "Rapport Vertical (VR)", "unit": "%", "ref": "Cavagna", "def": "Ratio entre l'oscillation verticale et la longueur de foulée. Mesure le pourcentage de gaspillage énergétique vers le haut."},
    "VO": {"blue": 8.5, "green": 10.5, "label": "Oscillation Vert.", "unit": "cm", "ref": "Moore (2016)", "def": "Hauteur brute du déplacement vertical du centre de masse à chaque foulée."},
    "GCT": {"blue": 240, "green": 280, "label": "Contact Sol", "unit": "ms", "ref": "Scientific DB", "def": "Durée d'appui du pied au sol. Un temps court est synonyme de réactivité neuromusculaire et de renvoi élastique."},
    "CADENCE": {"blue": 175, "green": 165, "label": "Cadence", "unit": "spm", "ref": "Jack Daniels", "def": "Fréquence des pas par minute. Une foulée économique internationale cible une fréquence proche de 170-180 spm."},
    "TRIMP": {"blue": 100, "green": 180, "label": "Charge (TRIMP)", "unit": "pts", "ref": "Morton (1991)", "def": "Modélisation de la charge d'entraînement combinant la durée de l'effort et l'intensité cardiaque relative."}
}

def get_status(val, key):
    n = NORMS[key]
    if key in ["CADENCE", "W/KG"]:
        if val >= n["blue"]: return "🔵", 100
        if val >= n["green"]: return "🟢", 60
        return "🔴", 30
    else:
        if val <= n["blue"]: return "🔵", 100
        if val <= n["green"]: return "🟢", 60
        return "🔴", 30

def afficher_un_kpi_aligne(col_st, titre, valeur, status_tuple):
    icon_status = status_tuple[0]
    tendancy = "↑" if status_tuple[1] >= 60 else "↓"
    with col_st:
        st.markdown(f"""
        <div class="kpi-container">
            <div style="font-size: 0.85em; color: #94a3b8; text-transform: uppercase; text-align: center;">{titre}</div>
            <div style="font-size: 1.8em; font-weight: bold; margin: 5px 0; text-align: center;">{valeur}</div>
            <div class="status-row"><span class="trend-arrow">{tendancy}</span><span class="status-circle">{icon_status}</span></div>
        </div>
        """, unsafe_allow_html=True)

def extraire_donnees_robuste(uploaded_file):
    raw_bytes = uploaded_file.getvalue().replace(b'\x00', b'')
    text = raw_bytes.decode('utf-8-sig', errors='ignore')
    text_fixed = re.sub(r'"[^"]*"', lambda m: m.group(0).replace('\n', ' ').replace('\r', ''), text)
    lines = text_fixed.splitlines()
    h_idx = next((i for i, l in enumerate(lines[:20]) if any(kw in l for kw in ["Durée", "Distance", "Circuits"])), 0)
    data_io = io.StringIO("\n".join(lines[h_idx:]))
    df = pd.DataFrame(list(csv.reader(data_io, delimiter=',', quotechar='"')))
    df.columns = df.iloc[0]
    df = df[1:].copy()
    df.columns = [re.sub(r'\s+', ' ', str(c)).strip() for c in df.columns]
    for col in df.columns:
        df[col] = df[col].apply(lambda x: str(x).replace(',', '.') if isinstance(x, str) else x)
    return df

# --- INTERFACE ET ROUTAGE ---
st.set_page_config(page_title="TrainSmart-dz v7.1", layout="wide")
init_db()

with st.sidebar:
    if os.path.exists(LOGO_PATH):
        st.image(LOGO_PATH, use_container_width=True)
    st.header("👤 Profil Athlète")
    prenom = st.text_input("Prénom", "Athlète")
    nom = st.text_input("Nom", "Expert")
    sexe = st.selectbox("Sexe", ["Homme", "Femme"])
    age = st.number_input("Âge", value=47)
    taille = st.number_input("Taille (cm)", value=175)
    poids = st.number_input("Poids (kg)", value=72.0)
    fc_max = st.number_input("FC Max", value=185)
    date_seance = st.sidebar.date_input("📅 Date de la séance", datetime.date.today())
    st.markdown("---")
    menu = st.radio("Navigation", ["Analyse de Séance", "Référentiel & Zones", "Historique"])

nom_complet = f"{prenom} {nom}"

if menu == "Analyse de Séance":
    st.title("Analyse de Performance")
    up = st.file_uploader("Importer CSV Garmin", type="csv", key="file_uploader")

    if up is not None:
        if 'df_analyse' not in st.session_state or st.session_state.filename != up.name:
            st.session_state.df_analyse = extraire_donnees_robuste(up)
            st.session_state.filename = up.name

    if 'df_analyse' in st.session_state and st.session_state.df_analyse is not None:
        df = st.session_state.df_analyse

        def trouver_col(mots, colonnes):
            for m in mots:
                for c in colonnes:
                    if m.lower() in c.lower(): return c
            return None

        c_dur = trouver_col(["Durée", "Time"], df.columns)
        c_dist = trouver_col(["Distance"], df.columns)
        c_pwr = trouver_col(["Puissance moyenne", "Power"], df.columns)
        c_fc = trouver_col(["Fréquence cardiaque moyenne", "HR"], df.columns)
        c_gct = trouver_col(["Temps de contact", "GCT"], df.columns)
        c_cad = trouver_col(["Cadence"], df.columns)
        c_vr = trouver_col(["Rapport vertical", "Vertical Ratio"], df.columns)
        c_vo = trouver_col(["Oscillation verticale"], df.columns)

        potential_phases = ["Type d'étape", "Type d'intervalle", "Phase", "Circuits"]
        group_col = next((c for c in potential_phases if c in df.columns), df.columns[0])

        for phase, group in df.groupby(group_col):
            if str(phase).lower() in ["récapitulatif", "total"] or len(group) < 1: continue
            t_sec = group[c_dur].apply(smart_parse_time).sum()
            if t_sec < 10: continue

            p_avg = pd.to_numeric(group[c_pwr], errors='coerce').mean() if c_pwr else 0
            fc_avg = pd.to_numeric(group[c_fc], errors='coerce').mean() if c_fc else 0
            dist_m = pd.to_numeric(group[c_dist], errors='coerce').sum() * 1000
            v_ms = dist_m / t_sec
            gct_avg = pd.to_numeric(group[c_gct], errors='coerce').mean() if c_gct else np.nan
            vr_avg = pd.to_numeric(group[c_vr], errors='coerce').mean() if c_vr else np.nan
            vo_avg = pd.to_numeric(group[c_vo], errors='coerce').mean() if c_vo else np.nan
            cad_avg = pd.to_numeric(group[c_cad], errors='coerce').mean() if c_cad else np.nan

            rei = p_avg / (poids * v_ms) if v_ms > 0 else 0
            w_kg = p_avg / poids if poids > 0 else 0
            trimp = (t_sec / 60) * (fc_avg / fc_max) * 1.5

            fc1 = pd.to_numeric(group[c_fc].iloc[:len(group)//2], errors='coerce').mean() if c_fc else 0
            fc2 = pd.to_numeric(group[c_fc].iloc[len(group)//2:], errors='coerce').mean() if c_fc else 0
            drift = ((fc2 - fc1)/fc1)*100 if fc1 and fc1 > 0 else 0

            stats = {k: get_status(v, k) for k, v in zip(NORMS.keys(), [rei, drift, w_kg, vr_avg, vo_avg, gct_avg, cad_avg, trimp])}
            score_global = sum(v[1] for v in stats.values()) / len(stats)

            with st.expander(f"PHASE : {str(phase).upper()} - Score Technique Global : {score_global:.1f}/100", expanded=True):
                r1_c1, r1_c2, r1_c3 = st.columns(3)
                afficher_un_kpi_aligne(r1_c1, "REI (Économie)", f"{rei:.3f}", stats["REI"])
                afficher_un_kpi_aligne(r1_c2, "Drift Cardio", f"+{drift:+.1f}%", stats["Pa:Hr"])
                afficher_un_kpi_aligne(r1_c3, "Power/Weight", f"{w_kg:.2f} W/kg", stats["W/KG"])

                st.markdown("<br>", unsafe_allow_html=True)

                r2_c1, r2_c2, r2_c3 = st.columns(3)
                if not np.isnan(vr_avg): afficher_un_kpi_aligne(r2_c1, "Rapport Vertical (VR)", f"{vr_avg:.1f}%", stats["VR"])
                if not np.isnan(vo_avg): afficher_un_kpi_aligne(r2_c2, "Oscillation Vert.", f"{vo_avg:.1f}cm", stats["VO"])
                if not np.isnan(gct_avg): afficher_un_kpi_aligne(r2_c3, "Contact Sol", f"{gct_avg:.0f}ms", stats["GCT"])

                st.markdown("<br>", unsafe_allow_html=True)

                r3_c1, r3_c2, r3_c3 = st.columns(3)
                afficher_un_kpi_aligne(r3_c1, "Charge TRIMP", f"{trimp:.0f}", stats["TRIMP"])
                afficher_un_kpi_aligne(r3_c2, "Cadence", f"{cad_avg:.0f}spm", stats["CADENCE"])
                with r3_c3:
                    st.markdown(f'<div class="kpi-container"><div style="font-size: 0.85em; color: #94a3b8;">VITESSE RÉELLE</div><div style="font-size: 1.8em; font-weight: bold;">{v_ms*3.6:.1f} km/h</div><div style="font-size: 1.2em;">🏃‍♂️</div></div>', unsafe_allow_html=True)
    else:
        st.info("👋 Bienvenue ! Veuillez charger votre fichier CSV Garmin dans la barre latérale pour débuter l'analyse.")

elif menu == "Référentiel & Zones":
    st.title("📚 Guide Méthodologique & Référentiel International")

    st.subheader("🔥 1. Plages de Fréquence Cardiaque (Standard Physiologique)")
    z_data = []
    zones = [("Z1", 0.5, 0.6, "Récupération active / Régénération métabolique"),
             ("Z2", 0.6, 0.7, "Endurance Fondamentale / Développement de la base aérobie"),
             ("Z3", 0.7, 0.8, "Tempo / Amélioration du rythme de croisière"),
             ("Z4", 0.8, 0.9, "Seuil Lactique / Travail de la clairance des lactates"),
             ("Z5", 0.9, 1.0, "VMA / Puissance Maximale Aérobie (Anoxie tolérée)")]
    for z, l, h, desc in zones:
        z_data.append({"Zone": z, "Plage BPM": f"{int(fc_max*l)} - {int(fc_max*h)}", "Pourcentage FC Max": f"{int(l*100)}% - {int(h*100)}%", "Objectif Physiologique": desc})
    st.table(pd.DataFrame(z_data))

    st.subheader("🎯 2. Seuils de Normalité Scientifique (Évaluation Couleur)")
    norm_data = []
    for k, v in NORMS.items():
        if k in ["CADENCE", "W/KG"]:
            norm_data.append({"Indicateur": v['label'], "🔵 Optimal (Bleu)": f"> {v['blue']}", "🟢 Correct (Vert)": f"{v['green']} - {v['blue']}", "🔴 Alerte (Rouge)": f"< {v['green']}", "Unité": v['unit']})
        else:
            norm_data.append({"Indicateur": v['label'], "🔵 Optimal (Bleu)": f"< {v['blue']}", "🟢 Correct (Vert)": f"{v['blue']} - {v['green']}", "🔴 Alerte (Rouge)": f"> {v['green']}", "Unité": v['unit']})
    st.table(pd.DataFrame(norm_data))

    st.subheader("🎓 3. Nomenclature, Définitions & Littérature Sportive")
    def_data = []
    for k, v in NORMS.items():
        def_data.append({"Indicateur": v['label'], "Description et Application": v['def'], "Référence Documentaire": v['ref']})
    st.table(pd.DataFrame(def_data))

elif menu == "Historique":
    st.title("📈 Évolution Technique")
    conn = sqlite3.connect(DB_PATH)
    h_df = pd.read_sql_query("SELECT * FROM evolution WHERE nom = ? ORDER BY date DESC", conn, params=(nom_complet,))
    conn.close()
    if not h_df.empty:
        st.line_chart(h_df.set_index('date')['score'])
        st.dataframe(h_df)
    else:
        st.info("Aucune donnée enregistrée dans la base SQL pour le moment.")
